### ISSUE TITLE
Scroll Buttons showing the menu.

### ISSUE THREAD

**Issue by dpereira411** [monyschuk/LITabControl#2]
The first mouse click on each scroll button seems to trigger the menu on some cases. 
http://i.imgur.com/g6xbCWO.png

**Comment by monyschuk** [comment]
Thanks - I'll give it a look

**Comment by monyschuk** [comment]
I'm not able to reproduce the issue, but sense this could be caused by menus associated with the control's default cell. To fix, I've explicitly cleared menus on the add button, scroll left and scroll right buttons when initially constructing the control's subviews. Please reopen the issue if your problem persists.

see: https://github.com/monyschuk/LITabControl/commit/3f50f1aded9753052bca64c7fe37ec937d746110
